name: Test Automation
on: 
  push:
    branches:
    -  main
  pull_request:
    branches: 
    -  main
jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
    -  name: Build Frontend
       run: cd frontend/
    -  run: go build frontend
  test:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
    -  name: Test Frontend
       run: cd frontend/
    -  run: go test frontend
    
    
